### ISSUE TITLE
Review the checklist

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/pre-meeting-checklist#1]
Everyone, please review the checklist at https://lsstdesc.github.io/pre-meeting-checklist/ before we send it out tomorrow. 

If you see any issues, feel free to comment here, open another issue, or submit an PR. 

LOC (@EiffL @duncandc): note that we are missing two links: the Zoom number page and the carpool page. Can you set them up? Thanks!

**Comment by katrinheitmann** [comment]
Very nice, thanks very much. I suppose you know that the car pool link doesn't work yet? Everything else seemed fine. Thanks again!

**Comment by yymao** [comment]
Thanks, Katrin. Yes there are two missing links at this moment (carpool and Zoom). I've pinged LOC.

**Comment by heather999** [comment]
Looks great!  The Zoom connection link still needs to be updated.  Is it out of bounds to add a bullet about uploading any slides/providing links to presentation materials on the appropriate Confluence agenda pages for those who are presenting during the sessions?

**Comment by rmandelb** [comment]
There actually is a car pool page already, it just wasn't linked in the top menu bar:
https://confluence.slac.stanford.edu/display/LSSTDESC/CMU+2018+-+Car+Pooling

I actually don't know how to modify the top menu bar without breaking it myself - is somebody in this thread able to do that?

Regarding the Zoom page, @EiffL or @duncandc can one of you please create it so that the people who will set up the Zoom numbers know how many to make?

**Comment by rmandelb** [comment]
> Is it out of bounds to add a bullet about uploading any slides/providing links to presentation 
> materials  on the appropriate Confluence agenda pages for those who are presenting during the 
> sessions?

Yes, that reminder has to be sent around; that's one of the usual "week before meeting" tasks.  The simplest way to do the presentations is link them from confluence so they can be downloaded and shown from the computer that is wired into the room sound system.

**Comment by yymao** [comment]
Thanks, @heather999 and @rmandelb. I've added an item about uploading talks. I've linked the carpool and zoom page (I created an [empty zoom page](https://confluence.slac.stanford.edu/x/cAE4Dg) to be filled out by the LOC).

Unrelated to this checklist, I also added both carpool and zoom pages to the banner on Confluence. 

(cc @EiffL @duncandc)

**Comment by rmandelb** [comment]
I filled in the rooms on the Zoom page; as you can see, we need 6 IDs for the main meeting rooms plus it would be nice to have a spare or two.

**Comment by yymao** [comment]
Last call to see if people have comments.

**Comment by EiffL** [comment]
@yymao Looks Good to me !

**Comment by drphilmarshall** [comment]
Me too - very nice. These emails are much appreciated, I think. Thank you!
